-- hr-recursive-subordinates.sql
-- Goal: Retrieve all employees, their levels in the organization, and their management path using a Recursive CTE.
-- 
-- Scenario: 
-- Table: Employees (id, name, manager_id)
-- 1. Identify the 'Anchor' (Top-level managers where manager_id is NULL).
-- 2. Recursively join the table to find subordinates.
-- 3. Output: id, name, level (1 for top), and path (e.g., 'CEO > Manager > Employee').
--
-- Reference: https://learnsql.com/blog/sql-cte-interview-questions/
