-- Reference: https://www.hackerrank.com/challenges/the-report/problem?isFullScreen=true
-- Topic: SQL Joins/Aggregates - Tier 2 SQL
-- Goal: Query the name, grade, and marks for students. If grade < 8, name = NULL. Sort by Grade DESC, Name ASC, Marks ASC.
-- TODO
